Cross validation is use to compare the mean score of different model in a particular dataset to determine which model will be best to predict the result

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_digits
digits=load_digits()

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)


In [4]:
Tr=tree.DecisionTreeClassifier()
Tr.fit(x_train,y_train)
Tr.score(x_test,y_test)

0.825

K fold is used to divide the datasets into multiple segment

In [5]:
from sklearn.model_selection import KFold
Kf=KFold(n_splits=3)
Kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [6]:
for train_index,test_index in Kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [7]:
def getscore(model,x_train,y_train,x_test,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

getscore(LogisticRegression(),x_train,y_train,x_test,y_test)



c:\Users\adelz\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9638888888888889

In [8]:
getscore(SVC(),x_train,y_train,x_test,y_test)

0.9805555555555555

In [9]:
getscore(RandomForestClassifier(),x_train,y_train,x_test,y_test)

0.9722222222222222

In [10]:
getscore(tree.DecisionTreeClassifier(),x_train,y_train,x_test,y_test)

0.85

test and train set can be split in diffirent segment through different section

In [11]:
from sklearn.model_selection import StratifiedKFold

folds= StratifiedKFold(n_splits=3)

Sc_logist=[]
Sc_svm=[]
Sc_rf=[]
Sc_dt=[]

for train_index,test_index in folds.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    Sc_logist.append(getscore(LogisticRegression(),x_train,y_train,x_test,y_test))
    Sc_svm.append(getscore(SVC(),x_train,y_train,x_test,y_test))
    Sc_rf.append(getscore(RandomForestClassifier(),x_train,y_train,x_test,y_test))
    Sc_dt.append(getscore(tree.DecisionTreeClassifier(),x_train,y_train,x_test,y_test))



c:\Users\adelz\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\adelz\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [12]:
Sc_logist

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [13]:
Sc_dt

[0.7429048414023373, 0.8263772954924875, 0.7729549248747913]

In [14]:
Sc_rf

[0.9365609348914858, 0.9482470784641068, 0.9298831385642737]

In [15]:
Sc_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [16]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=5)

c:\Users\adelz\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\adelz\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [17]:
Scr1=cross_val_score(LogisticRegression(),digits.data,digits.target,cv=5)
np.average(Scr1)

c:\Users\adelz\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\adelz\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

0.9137650882079852

In [18]:
Scr2=cross_val_score(SVC(),digits.data,digits.target,cv=5)
np.average(Scr2)

0.9632838130609718

In [19]:
Scr3=cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=5)
np.average(Scr3)

0.9388099659548128

In [20]:
Scr4=cross_val_score(tree.DecisionTreeClassifier(),digits.data,digits.target,cv=5)
np.average(Scr4)

0.7857938718662952