In [83]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

df=pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [84]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [85]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [86]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.Message,df.spam,test_size=0.25)
X_train

2073                              That is wondarfull song
2048    No de. But call me after some time. Ill tell y...
2716    Cool. I am  &lt;#&gt;  inches long. hope you l...
3255               I can make lasagna for you... vodka...
1108    From someone not to smoke when every time I've...
                              ...                        
4626                             I'm on the bus. Love you
3006                              Ew are you one of them?
2719    18 days to Euro2004 kickoff! U will be kept in...
3165    TODAY is Sorry day.! If ever i was angry with ...
3702                                Shall i get my pouch?
Name: Message, Length: 4179, dtype: object

As we can see that our feature data is text which is why we will use count Vectorizer tecquine for each coloumn data of Message Coloumn



In [87]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_count=v.fit_transform(X_train.values)
X_test_count=v.fit_transform(X_test.values)
X_train_count.toarray()[:6]


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In pipeline we dont need to transform our features data individually to CountVectorizer here pipeline convert it to the CountVectorizer inside the model

In [88]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
model=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('classifier',MultinomialNB())
])
model.fit(X_train,Y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classifier', MultinomialNB())])

In [89]:
X_test_count.toarray()[:6]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [90]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [91]:
model.score(X_test,Y_test)

0.9827709978463748